version: "3.7"
services:
    employee:
        build:
            context: ./
            dockerfile: Dockerfile
        image: employee
        container_name: employee-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - employee

    db:
        image: mysql:8
        command: --max_allowed_packet=32505856
        container_name: employee-db
        restart: unless-stopped
        ports:
            - "3400:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-volumes/mysql:/var/lib/mysql
        networks:
            - employee

    nginx:
        image: nginx:alpine
        container_name: employee-nginx
        restart: unless-stopped
        ports:
            - "9000:80"
        volumes:
            - ./:/var/www
            - ./docker-volumes/nginx:/etc/nginx/conf.d/
        networks:
            - employee

networks:
    employee:
        driver: bridge
