version: "3.7"
services:
    import:
        build:
            context: ./
            dockerfile: Dockerfile
        image: import
        container_name: import-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - import

    db:
        image: mysql:8
        command: --max_allowed_packet=32505856
        container_name: import-db
        restart: unless-stopped
        ports:
            - "3400:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-volumes/mysql-dump:/docker-entrypoint-initdb.d
            - ./docker-volumes/mysql:/var/lib/mysql
        networks:
            - import

    redis:
        container_name: import-redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./docker-volumes/redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always
        networks:
            - import

    nginx:
        image: nginx:alpine
        container_name: import-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-volumes/nginx:/etc/nginx/conf.d/
        networks:
            - import

networks:
    import:
        driver: bridge
